//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID_Item { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ID_Structure { get; set; }
        public int ID_Specific { get; set; }
        public double Mass { get; set; }
        public double SizeH { get; set; }
        public double SizeW { get; set; }
        public int ID_Owner { get; set; }
    
        public virtual Owner Owner { get; set; }
        public virtual Specific Specific { get; set; }
        public virtual Structure Structure { get; set; }
    }
}
