//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID_Item { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Count { get; set; }
        public int Price { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> ID_Act { get; set; }
        public Nullable<int> Specific { get; set; }
    
        public virtual LoadAct LoadAct { get; set; }
        public virtual Unit Unit1 { get; set; }
        public virtual Specific Specific1 { get; set; }
    }
}
