//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab1.Model
{
    using System;
    using System.Collections.Generic;
    using lab1.Model;
    using System.Collections.ObjectModel;
    using System.Data.Entity;

    public partial class LoadAct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoadAct()
        {
            this.Item = new HashSet<Item>();
        }
    
        public int ID_Pocket { get; set; }
        public System.DateTime LoadDate { get; set; }
        public Nullable<int> ID_Structure { get; set; }
        public Nullable<int> ID_Owner { get; set; }
        public Nullable<int> Provider { get; set; }

        public Nullable<int> Sum { get
            {
                return PageMain.ActSum(this);
            } }
        public Nullable<int> Count
        {
            get
            {
                return PageMain.ActCount(this);
            }
        }

        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Item { get; set; }
        public virtual Structure Structure { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
