//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public int ID_Producer { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<int> AddedBy { get; set; }
    
        public virtual Account Account { get; set; }
        override
        public string ToString() => this.Name;
    }
}
