//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SKLAD_WPF : DbContext
    {
        public SKLAD_WPF()
            : base("name=SKLAD_WPF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<LoadAct> LoadAct { get; set; }
        public virtual DbSet<Specific> Specific { get; set; }
        public virtual DbSet<Structure> Structure { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
    }
}
